spring.application.name=backend

server.port=8080
server.servlet.context-path=/api

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.url=jdbc:postgresql://localhost:5432/latex
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secretKey=
auth.accessTokenValidity=30m
auth.refreshTokenValidity=5h

# Database
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=${DB_URL}
#spring.data.mongodb.username=${DB_USER}
#spring.data.mongodb.password=${DB_PASSWORD}